### ISSUE TITLE
Initial Model view stuck loading

### ISSUE THREAD

**Issue by RyugaX** [canonical/jaas-dashboard#1223] opened 2022-03-25 10:30 UTC
Hi,
I'm a new user and upon entering https://jaas.ai/models I've been asked to login, I created a new Ubuntu One account and I've been granted access. The problem is that the model view never stops loading. I tried to refresh and reenter (same user) with a fresh new incognito window. Same result.
![image](https://user-images.githubusercontent.com/18050077/160104058-e7d214f0-2db9-4d08-b25f-0a2c55c8ff3a.png)

**Comment by huwshimi** [comment] 2022-09-20 04:38
Duplicate of: https://github.com/canonical/jaas-dashboard/issues/1012.

**Closed by huwshimi** 2022-09-20 04:38 UTC
